networks:
  lopet-network:
    driver: bridge

volumes:
  lopet-mysql-data:
  caddy_data:
  caddy_config:

services:
  lopet-mysql:
    image: mysql:8.4
    container_name: lopet-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - lopet-mysql-data:/var/lib/mysql
    mem_limit: 600m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATABASE_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lopet-network

  lopet-redis:
    image: redis:8.0
    container_name: lopet-redis
    restart: always
    mem_limit: 100m
    networks:
      - lopet-network

  lopet-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lopet-backend
    restart: always
    env_file:
      - .env.dev
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}   # lấy từ .env, không hardcode
    expose:
      - "8080"
    depends_on:
      lopet-mysql:
        condition: service_healthy
      lopet-redis:
        condition: service_started
    mem_limit: 1200m
    networks:
      - lopet-network

  lopet-caddy:
    image: caddy:2-alpine
    container_name: lopet-caddy
    profiles: ["proxy"]
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - lopet-network
